### ISSUE TITLE
Feature: Option to disable auto-resume music on Sonos

### ISSUE THREAD

**Issue by alexruffell** [rayzurbock/SmartThings-BigTalker-Orig#21]
For many months now I have been having issues with BigTalker resuming music that was not playing on the Sonos speaker dedicated for home automation messages. Sometimes it works great, other times it just won't stop playing music after playing an alert/message. No idea why... however I figured it would be nice to have a simple option to switch the resume functionality on/off so whether this issue gets resolved or whether this is an ST problem or a SmartApp problem, it really no longer matters :)

**Comment by rayzurbock** [comment]
I'll add this "defaults" option to enable/disable resume when using a musicPlayer device handler in the 1.1.6 release.

**Comment by rayzurbock** [comment]
I plan to release 1.1.6 to resolve a couple of bugs.  Therefore, I'm changing my original plan for this feature from release with 1.1.6 to release with 1.1.7 as I will likely need to adjust several portions of the Talk() function and ensure that the new setting is backwards compatible for a while.

**Comment by alexruffell** [comment]
Thank you for the consideration. The resuming of music i was not playing is really getting to me. I wonder if it could have anything to do with BigTalker checking whether it the Sonos is playing while it is playing a BigTalker alert in which case it would explain why opening and closing a door with two messages back to back often ends up with Pandora blasting off some classical music (I left it on that as it is way less disrupting that some other music... especially when unexpected). Rumors are starting to spread that my house is infested with a musical poltergeist.
