### ISSUE TITLE
Contact Group 3

### ISSUE THREAD

**Issue by bucks7756** [rayzurbock/SmartThings-BigTalker-Orig#22]
Contact group 3 does not work.

**Comment by rayzurbock** [comment]
Bug confirmed.
Typo found.
Will resolve in next release.

BigTalker 1.1.5, Line 2561 currently reads:
`def onContactEvent(evt){`
Should be:
`def onContact3Event(evt){`

**Comment by rayzurbock** [comment]
Beta version posted here:  https://github.com/rayzurbock/SmartThings-BigTalker/tree/1.1.6-Beta
Please test and let me know if you find this issue now resolved.

**Comment by bucks7756** [comment]
Works fine.  Thanks.
--------------------------------------------
On Fri, 3/18/16, Brian Lowrance <notifications@github.com> wrote:

 Subject: Re: [SmartThings-BigTalker] Contact Group 3 (#22)
 To: "rayzurbock/SmartThings-BigTalker" <SmartThings-BigTalker@noreply.github.com>
 Cc: "bucks7756" <bucks7756@yahoo.com>
 Date: Friday, March 18, 2016, 9:58 PM
 
 Beta version posted here:  https://github.com/rayzurbock/SmartThings-BigTalker/tree/1.1.6-Beta
 
 Please test and let me know if you find this issue now
 resolved.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly or view
 it on GitHub

**Comment by waldo68** [comment]
I am also not able to get contact group 3 to work. I have the most recent version installed. Also under the IDE page the third contact shows no Handler under Event Subscriptions.

**Comment by rayzurbock** [comment]
@waldo68 This version & GitHub thread is no longer active.  Please see [Big Talker 1.1.12](https://github.com/rayzurbock/SmartThings-BigTalker).  1.1.12 is soon to be obsolete (no further work is being done for it).  The latest version is the development version 2.0.x which can be [found here](https://github.com/rayzurbock/SmartThings-BigTalker/tree/development/smartapps/rayzurbock)
